"""Explanation-ready sample helpers built on top of replayed run bundles."""

from traffic_graph.explain.explanation_samples import (
    build_explanation_samples,
    export_explanation_candidates,
    select_balanced_samples_for_explanation,
    select_top_alert_samples,
    sort_samples_by_score,
    summarize_explanation_samples,
    summarize_explanation_samples_text,
)
from traffic_graph.explain.explanation_types import (
    ExplanationSample,
    ExplanationSampleSummary,
    ExplanationScope,
)
from traffic_graph.explain.path_extractor import (
    extract_rule_for_sample,
    extract_rules_for_samples,
)
from traffic_graph.explain.prompt_builder import (
    build_prompt_input,
    build_prompt_inputs,
    build_prompt_text,
    build_rule_summary,
    build_structured_context,
    export_prompt_inputs,
)
from traffic_graph.explain.prompt_dataset import (
    build_prompt_dataset,
    select_prompt_samples,
    sort_prompt_inputs_by_score,
    summarize_prompt_dataset,
    summarize_prompt_dataset_text,
)
from traffic_graph.explain.prompt_replay import (
    filter_prompt_records,
    get_prompt_record,
    list_prompt_records,
    load_prompt_dataset,
    summarize_prompt_dataset as summarize_prompt_dataset_replay,
    summarize_prompt_dataset_text as summarize_prompt_dataset_replay_text,
)
from traffic_graph.explain.prompt_export import (
    PromptDatasetExportResult,
    export_prompt_dataset,
)
from traffic_graph.explain.llm_result_export import (
    LLMResultExportResult,
    export_llm_results,
    summarize_llm_results_text,
)
from traffic_graph.explain.llm_results import (
    LLMResultArtifact,
    LLMResultRecord,
    LLMResultStatus,
    LLMResultSummary,
    LLM_RESULT_ARTIFACT_FIELDS,
    LLM_RESULT_FIELDS,
    LLM_RESULT_STATUS_VALUES,
    LLM_RESULT_SUMMARY_FIELDS,
    summarize_llm_results,
)
from traffic_graph.explain.llm_runner_stub import run_llm_stub
from traffic_graph.explain.prompt_replay_types import (
    PromptDatasetManifestInfo,
    PromptDatasetReplay,
    PromptDatasetView,
)
from traffic_graph.explain.prompt_types import (
    PROMPT_ALERT_SUMMARY_FIELDS,
    PROMPT_BASIC_INFO_FIELDS,
    PROMPT_CONTEXT_FIELDS,
    PROMPT_INPUT_FIELDS,
    PROMPT_RULE_SUMMARY_FIELDS,
    PROMPT_SCORE_SUMMARY_FIELDS,
    PromptDatasetArtifact,
    PromptDatasetSelectionMode,
    PromptDatasetSummary,
    PromptInput,
    PromptScope,
)
from traffic_graph.explain.rule_records import (
    RULE_PATH_CONDITION_FIELDS,
    RULE_RECORD_FIELDS,
    RulePathCondition,
    RuleRecord,
    RuleRecordSummary,
    export_rule_records,
    summarize_rule,
    summarize_rules,
)
from traffic_graph.explain.surrogate_tree import (
    extract_training_matrix,
    load_surrogate_tree_artifact,
    save_surrogate_tree_artifact,
    summarize_surrogate_tree_artifact,
    train_surrogate_tree,
)
from traffic_graph.explain.surrogate_types import (
    SurrogateTrainingMatrix,
    SurrogateTreeArtifact,
    SurrogateTreeConfig,
    SurrogateTreeMode,
    SurrogateTreeSaveResult,
    SurrogateTreeSummary,
)

__all__ = [
    "ExplanationSample",
    "ExplanationSampleSummary",
    "ExplanationScope",
    "PromptInput",
    "PromptDatasetArtifact",
    "PromptDatasetExportResult",
    "PromptDatasetManifestInfo",
    "PromptDatasetReplay",
    "PromptDatasetSelectionMode",
    "PromptDatasetSummary",
    "PromptDatasetView",
    "PromptScope",
    "LLMResultArtifact",
    "LLMResultExportResult",
    "LLMResultRecord",
    "LLMResultStatus",
    "LLMResultSummary",
    "LLM_RESULT_ARTIFACT_FIELDS",
    "LLM_RESULT_FIELDS",
    "LLM_RESULT_STATUS_VALUES",
    "LLM_RESULT_SUMMARY_FIELDS",
    "PROMPT_ALERT_SUMMARY_FIELDS",
    "PROMPT_BASIC_INFO_FIELDS",
    "PROMPT_CONTEXT_FIELDS",
    "PROMPT_INPUT_FIELDS",
    "PROMPT_RULE_SUMMARY_FIELDS",
    "PROMPT_SCORE_SUMMARY_FIELDS",
    "RulePathCondition",
    "RuleRecord",
    "RuleRecordSummary",
    "RULE_PATH_CONDITION_FIELDS",
    "RULE_RECORD_FIELDS",
    "build_explanation_samples",
    "build_prompt_input",
    "build_prompt_inputs",
    "build_prompt_dataset",
    "build_prompt_text",
    "filter_prompt_records",
    "build_rule_summary",
    "build_structured_context",
    "export_llm_results",
    "get_prompt_record",
    "export_explanation_candidates",
    "export_prompt_dataset",
    "list_prompt_records",
    "export_prompt_inputs",
    "export_rule_records",
    "load_prompt_dataset",
    "extract_rule_for_sample",
    "extract_rules_for_samples",
    "select_prompt_samples",
    "select_balanced_samples_for_explanation",
    "select_top_alert_samples",
    "sort_samples_by_score",
    "sort_prompt_inputs_by_score",
    "summarize_explanation_samples",
    "summarize_explanation_samples_text",
    "summarize_prompt_dataset",
    "summarize_prompt_dataset_replay",
    "summarize_prompt_dataset_replay_text",
    "summarize_prompt_dataset_text",
    "summarize_llm_results",
    "summarize_llm_results_text",
    "summarize_rule",
    "summarize_rules",
    "SurrogateTrainingMatrix",
    "SurrogateTreeArtifact",
    "SurrogateTreeConfig",
    "SurrogateTreeMode",
    "SurrogateTreeSaveResult",
    "SurrogateTreeSummary",
    "extract_training_matrix",
    "load_surrogate_tree_artifact",
    "save_surrogate_tree_artifact",
    "summarize_surrogate_tree_artifact",
    "run_llm_stub",
    "train_surrogate_tree",
]
