"""Stub runner that converts prompt datasets into mock LLM results."""

from __future__ import annotations

from datetime import datetime, timezone

from traffic_graph.explain.llm_results import (
    LLMResultArtifact,
    LLMResultRecord,
    LLMResultSummary,
    summarize_llm_results,
)
from traffic_graph.explain.prompt_replay_types import PromptDatasetReplay
from traffic_graph.explain.prompt_types import PromptInput


def _timestamp_token(value: object | None) -> str:
    """Normalize a timestamp into a stable UTC token."""

    if value is None:
        moment = datetime.now(timezone.utc)
    elif isinstance(value, datetime):
        moment = value.astimezone(timezone.utc)
    else:
        token = str(value).strip()
        if token:
            return token
        moment = datetime.now(timezone.utc)
    return moment.strftime("%Y%m%dT%H%M%SZ")


def _compact_excerpt(text: str, *, limit: int = 240) -> str:
    """Collapse prompt text into a short single-line excerpt."""

    normalized = " ".join(text.split())
    if len(normalized) <= limit:
        return normalized
    if limit <= 3:
        return normalized[:limit]
    return normalized[: limit - 3] + "..."


def _build_response_text(
    prompt: PromptInput,
    *,
    model_name: str,
) -> str:
    """Render a deterministic mock response text for one prompt."""

    excerpt = _compact_excerpt(prompt.prompt_text)
    lines = [
        "MOCK LLM RESPONSE",
        f"prompt_id: {prompt.prompt_id}",
        f"run_id: {prompt.run_id}",
        f"model_name: {model_name}",
        f"scope: {prompt.scope}",
        f"anomaly_score: {prompt.anomaly_score:.6f}",
        f"is_alert: {prompt.is_alert}",
        "",
        "Prompt excerpt:",
        excerpt,
    ]
    return "\n".join(lines)


def _build_raw_response(
    prompt: PromptInput,
    *,
    model_name: str,
    response_text: str,
) -> dict[str, object]:
    """Build a structured mock response payload."""

    return {
        "stub": True,
        "model_name": model_name,
        "prompt_id": prompt.prompt_id,
        "run_id": prompt.run_id,
        "scope": prompt.scope,
        "prompt_text_length": len(prompt.prompt_text),
        "prompt_text_excerpt": _compact_excerpt(prompt.prompt_text),
        "response_text_length": len(response_text),
    }


def run_llm_stub(
    prompt_dataset_replay: PromptDatasetReplay,
    *,
    model_name: str = "mock-llm-stub",
    created_at: object | None = None,
) -> LLMResultArtifact:
    """Produce deterministic mock LLM results for a replayed prompt dataset."""

    created_at_token = _timestamp_token(created_at)
    result_records: list[LLMResultRecord] = []
    notes = [
        "This artifact was generated by the stub runner; no external LLM call was made."
    ]
    for prompt in prompt_dataset_replay.prompt_records:
        response_text = _build_response_text(prompt, model_name=model_name)
        raw_response = _build_raw_response(
            prompt,
            model_name=model_name,
            response_text=response_text,
        )
        result_records.append(
            LLMResultRecord(
                response_id=f"llm:{model_name}:{prompt.prompt_id}",
                prompt_id=prompt.prompt_id,
                run_id=prompt.run_id,
                model_name=model_name,
                response_text=response_text,
                raw_response=raw_response,
                status="success",
                error_message=None,
                created_at=created_at_token,
            )
        )

    summary = summarize_llm_results(result_records)
    source_summary = prompt_dataset_replay.selection_summary
    artifact_id = f"llm-results:{prompt_dataset_replay.dataset_id}:{model_name}"
    return LLMResultArtifact(
        result_id=artifact_id,
        run_id=prompt_dataset_replay.run_id,
        model_name=model_name,
        created_at=created_at_token,
        source_prompt_dataset_id=prompt_dataset_replay.dataset_id,
        source_prompt_dataset_run_id=prompt_dataset_replay.run_id,
        source_prompt_dataset_timestamp=prompt_dataset_replay.timestamp,
        source_prompt_dataset_scope=prompt_dataset_replay.manifest.scope,
        source_prompt_dataset_selection_mode=prompt_dataset_replay.manifest.selection_mode,
        result_count=len(result_records),
        result_records=tuple(result_records),
        summary=LLMResultSummary(
            total_count=summary.total_count,
            status_counts=summary.status_counts,
            success_count=summary.success_count,
            failed_count=summary.failed_count,
            skipped_count=summary.skipped_count,
            model_name=model_name,
            created_at=created_at_token,
            source_prompt_dataset_id=prompt_dataset_replay.dataset_id,
            source_prompt_dataset_scope=prompt_dataset_replay.manifest.scope,
            preview_prompt_ids=summary.preview_prompt_ids,
            preview_response_ids=summary.preview_response_ids,
        ),
        notes=tuple(notes),
        metadata={
            "runner": "stub",
            "prompt_count": source_summary.total_count,
            "alert_count": source_summary.alert_count,
            "labeled_count": source_summary.labeled_count,
        },
    )


__all__ = [
    "run_llm_stub",
]
